#!/usr/bin/env bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Define the custom header value
hostname=$(hostname)

# Configure Nginx to add the custom header
echo "add_header X-Served-By $hostname;" | sudo tee -a /etc/nginx/nginx.conf

# Restart Nginx to apply changes
sudo systemctl restart nginx
